In [1]:
import numpy as np
import pandas as pd

In [2]:
ds = pd.read_csv(r"C:\Users\Anantha Priya\Desktop\Final-Project\reviews.csv", delimiter = ",")

In [3]:
ds

asin               name  rating                date  verified  \
0      B0000SX2UC              Janet       3    October 11, 2005     False   
1      B0000SX2UC         Luke Wyatt       1     January 7, 2004     False   
2      B0000SX2UC             Brooke       5   December 30, 2003     False   
3      B0000SX2UC      amy m. teague       3      March 18, 2004     False   
4      B0000SX2UC      tristazbimmer       4     August 28, 2005     False   
...           ...                ...     ...                 ...       ...   
67981  B081H6STQQ              jande       5     August 16, 2019     False   
67982  B081H6STQQ            2cool4u       5  September 14, 2019     False   
67983  B081H6STQQ              simon       5       July 14, 2019     False   
67984  B081TJFVCJ  Tobiasz Jedrysiak       5   December 24, 2019      True   
67985  B0825BB7SG      Owen Gonzalez       5   December 11, 2019     False   

                                                   title  \
0                            Def not best, but not worst   
1                            Text Messaging Doesn't Work   
2                                        Love This Phone   
3                                Love the Phone, BUT...!   
4           Great phone service and options, lousy case!   
...                                                  ...   
67981  Awesome Phone, but finger scanner is a big mis...   
67982                                    Simply Amazing!   
67983  great phon3, but many bugs need to fix. still ...   
67984                                  Phone is like new   
67985                    Outstanding phone for the price   

                                                    body  helpfulVotes  
0      I had the Samsung A600 for awhile which is abs...           1.0  
1      Due to a software issue between Nokia and Spri...          17.0  
2      This is a great, reliable phone. I also purcha...           5.0  
3      I love the phone and all, because I really did...           1.0  
4      The phone has been great for every purpose it ...           1.0  
...                                                  ...           ...  
67981  I love the camera on this phone. The screen is...           1.0  
67982  I've been an Xperia user for several years and...           1.0  
67983                         buy one more for my cousin           NaN  
67984  Product looks and works like new. Very much re...           NaN  
67985  I love the size and style of this phone. It is...           NaN  

[67986 rows x 8 columns]

In [4]:
ds.drop(columns=['asin', 'name' , 'date' , 'verified' , 'helpfulVotes' ] , inplace = True)

In [5]:
ds

rating                                              title  \
0           3                        Def not best, but not worst   
1           1                        Text Messaging Doesn't Work   
2           5                                    Love This Phone   
3           3                            Love the Phone, BUT...!   
4           4       Great phone service and options, lousy case!   
...       ...                                                ...   
67981       5  Awesome Phone, but finger scanner is a big mis...   
67982       5                                    Simply Amazing!   
67983       5  great phon3, but many bugs need to fix. still ...   
67984       5                                  Phone is like new   
67985       5                    Outstanding phone for the price   

                                                    body  
0      I had the Samsung A600 for awhile which is abs...  
1      Due to a software issue between Nokia and Spri...  
2      This is a great, reliable phone. I also purcha...  
3      I love the phone and all, because I really did...  
4      The phone has been great for every purpose it ...  
...                                                  ...  
67981  I love the camera on this phone. The screen is...  
67982  I've been an Xperia user for several years and...  
67983                         buy one more for my cousin  
67984  Product looks and works like new. Very much re...  
67985  I love the size and style of this phone. It is...  

[67986 rows x 3 columns]

In [6]:
ds['sentiment'] = ds['rating'].apply(lambda rating : +1 if rating > 3 else 0)

In [7]:
ds

rating                                              title  \
0           3                        Def not best, but not worst   
1           1                        Text Messaging Doesn't Work   
2           5                                    Love This Phone   
3           3                            Love the Phone, BUT...!   
4           4       Great phone service and options, lousy case!   
...       ...                                                ...   
67981       5  Awesome Phone, but finger scanner is a big mis...   
67982       5                                    Simply Amazing!   
67983       5  great phon3, but many bugs need to fix. still ...   
67984       5                                  Phone is like new   
67985       5                    Outstanding phone for the price   

                                                    body  sentiment  
0      I had the Samsung A600 for awhile which is abs...          0  
1      Due to a software issue between Nokia and Spri...          0  
2      This is a great, reliable phone. I also purcha...          1  
3      I love the phone and all, because I really did...          0  
4      The phone has been great for every purpose it ...          1  
...                                                  ...        ...  
67981  I love the camera on this phone. The screen is...          1  
67982  I've been an Xperia user for several years and...          1  
67983                         buy one more for my cousin          1  
67984  Product looks and works like new. Very much re...          1  
67985  I love the size and style of this phone. It is...          1  

[67986 rows x 4 columns]

In [8]:
ds.isnull().any()

rating       False
title         True
body          True
sentiment    False
dtype: bool

In [9]:
ds["title"].fillna(ds["title"].mode()[0] , inplace = True)

In [10]:
ds["body"].fillna(ds["body"].mode()[0] , inplace = True)

In [11]:
ds.isnull().any()

rating       False
title        False
body         False
sentiment    False
dtype: bool

In [12]:
import re #regular expressions to replace special charecters
import nltk
nltk.download("stopwords") # for is then that or , is here where
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to C:\Users\Anantha
[nltk_data]     Priya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
ps = PorterStemmer()
data = []

In [14]:
for i in range(0,67986):
    review = ds["title"][i]
    review = re.sub('[^a-zA-Z]', ' ',review)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    data.append(review)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
import pickle 
cv = CountVectorizer(max_features = 3000)
x = cv.fit_transform(data).toarray()
with open('CountVectorizer','wb') as file:
    pickle.dump(cv,file)

In [16]:
y = ds.iloc[:,3:4].values

In [17]:
y

array([[0],
       [0],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 0,test_size = 0.2)

In [19]:
x_train.shape

(54388, 3000)

In [20]:
x_test.shape

(13598, 3000)

In [21]:
y_train.shape

(54388, 1)

In [22]:
y_test.shape

(13598, 1)

In [23]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(units = 3000 ,init = "random_uniform",activation = "relu"))
model.add(Dense(units = 4500 ,init = "random_uniform",activation = "relu"))

Using TensorFlow backend.
C:\Users\Anantha Priya\miniconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Anantha Priya\miniconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Anantha Priya\miniconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Anantha Priya\miniconda3\lib\site-packages\t

In [35]:
model.add(Dense(units = 1 ,init = "random_uniform",activation = "sigmoid"))
model.compile(optimizer = "adam",loss = "binary_crossentropy",metrics = ["accuracy"])
model.fit(x_train,y_train,epochs  = 20)

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\Anantha Priya\miniconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


Instructions for updating:
Use tf.cast instead.
Epoch 1/20
54388/54388 [==============================] - 960s 18ms/step - loss: 0.3437 - accuracy: 0.8509
Epoch 2/20
54388/54388 [==============================] - 1102s 20ms/step - loss: 0.2659 - accuracy: 0.8888
Epoch 3/20
54388/54388 [==============================] - 1178s 22ms/step - loss: 0.2047 - accuracy: 0.9177
Epoch 4/20
54388/54388 [==============================] - 1194s 22ms/step - loss: 0.1593 - accuracy: 0.9372
Epoch 5/20
54388/54388 [==============================] - 1121s 21ms/step - loss: 0.1378 - accuracy: 0.9460
Epoch 6/20
54388/54388 [==============================] - 1100s 20ms/step - loss: 0.1268 - accuracy: 0.9505
Epoch 7/20
54388/54388 [==============================] - 1994s 37ms/step - loss: 0.1193 - accuracy: 0.9526
Epoch 8/20
54388/54388 [==============================] - 997s 18ms/step - loss: 0.1161 - accuracy: 0.9532
Epoch 9/20
54388/54388 [==============================] - 1032s 19ms/step - loss: 0.1143 -

In [36]:
model.save("nlp.h5")

In [24]:
text =  "Hello, I have this phone and used it until I decided to buy a flip phone. I have had NO problems with the battery or new cases--it has a new fish case on "
text = re.sub('[^a-zA-Z]', ' ',text)
text = text.lower()
text = text.split()
text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
text = ' '.join(text)

In [60]:
y_p1 = model.predict(cv.transform([text]))

In [61]:
y_p1

array([[0.00312615]], dtype=float32)

In [62]:
y_p1>0.50.9572

array([[False]])

In [63]:
y_p1<0.5

array([[ True]])